### PR TITLE
Resolving JSHint errors

### PR DESCRIPTION
**Pull request by SteamingMutt**
Sorry if I fucked up the images, my upload screwed up and I can't recover because re-downloading yields the same results.

### CODE REVIEW

**Comment by TehSeph** [comment]
@SteamingMutt No worries about the images. Could you add another commit to fix them? Also, going from Array indexes to Object keys seems like it would break commands without some changes to the `neko.js` command parser. Have you checked this?

**Comment by TehSeph** [comment]
Furthermore, I'm in the middle of a rewrite and most of this is going to be changing. I'm still willing to merge this for now (once the concerns above are resolved) just in case anyone else wants to fork the bot before then, but just a heads up. :)

**Comment by SteamingMutt** [comment]
Just tested, doesn't break a thing.    
The reason why dot notation is better is because when java tries to access a property using a string literal within a pair of square brackets, and the property name is not a reserved word, you can just type them like this, as square brackets in this scenario are unnecessarily verbose and potentially confusing piece of code.   
Oh, and semicolons are just nice to have, even if they are not required in node.js :P

**Comment by SteamingMutt** [comment]
shia

Loving these results

**Comment by SteamingMutt** [comment]
Can't seem to be able to download not corrupted images, could you maybe send them to me @TehSeph?

**Comment by TehSeph** [comment]
Just grab them from [Master](https://github.com/TehSeph/Neko.js/tree/master/images)

**Comment by SteamingMutt** [comment]
That's the point, I get those corrupted results constantly

**Comment by TehSeph** [comment]
What... seriously? These are corrupt for you? They're fine for me.
bulli
shia
trash

**Comment by SteamingMutt** [comment]
Gotto love git, it's uploading incorrectly

**Comment by SteamingMutt** [comment]
I'll make a new fork and try again, seems I made a sync issue with git at the start.

**Pull request closed without merging**
