### PR TITLE
Resolving JSHint, again

### PR DESCRIPTION
**Pull request by SteamingMutt**
Without touching images this time

### CODE REVIEW

**Comment by TehSeph** [comment]
Why are you changing Ankouru?
アンコール = Ankōru, ō = oo/ou, Ankōru = Ankouru.

**Comment by SteamingMutt** [comment]
Oh shit, that's the best typo i've ever made

**Comment by TehSeph** [comment]
Also, `sadhorm` lol

**Comment by TehSeph** [comment]
Cool. Looks good.

**Pull request merged**
